using Microsoft.CodeAnalysis.Testing;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Threading.Tasks;
using VerifySourceGen = UnityStableReference.Tests.CSharpSourceGeneratorVerifier<
    UnityStableReference.StableWrapperSourceGenerator>;

namespace UnityStableReference.Tests;

[TestClass]
public class StableWrapperSourceGeneratorTests
{
    [TestMethod]
    public async Task GeneratesWrapperForClassWithGuidAttribute()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            namespace TestNamespace
            {
                [StableWrapperCodeGen, Guid("12345678-1234-1234-1234-123456789012")]
                public class TestClass
                {
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_12345678123412341234123456789012 : UnityStableReference.StableWrapper<TestNamespace.TestClass> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task GeneratesWrappersForMultipleClassesWithGuidAttribute()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            namespace TestNamespace
            {
                [StableWrapperCodeGen, Guid("AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE")]
                public class TestClass1
                {
                }

                [StableWrapperCodeGen, Guid("11111111-2222-3333-4444-555555555555")]
                public class TestClass2
                {
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_AAAAAAAABBBBCCCCDDDDEEEEEEEEEEEE : UnityStableReference.StableWrapper<TestNamespace.TestClass1> { }
            [System.Serializable] public class StableWrapper_11111111222233334444555555555555 : UnityStableReference.StableWrapper<TestNamespace.TestClass2> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task DoesNotGenerateWrapperForClassWithoutGuidAttribute()
    {
        // Arrange
        var source = """
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            namespace TestNamespace
            {
                [StableWrapperCodeGen]
                public class TestClass
                {
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task DoesNotGenerateWrapperWhenAssemblyAttributeIsMissing()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            namespace TestNamespace
            {
                [StableWrapperCodeGen, Guid("12345678-1234-1234-1234-123456789012")]
                public class TestClass
                {
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task GeneratesWrappersForNestedClasses()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            namespace TestNamespace
            {
                public class OuterClass
                {
                    [StableWrapperCodeGen, Guid("AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE")]
                    public class NestedClass
                    {
                    }
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_AAAAAAAABBBBCCCCDDDDEEEEEEEEEEEE : UnityStableReference.StableWrapper<TestNamespace.OuterClass.NestedClass> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task GeneratesWrapperForStructsWithGuidAttribute()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            namespace TestNamespace
            {
                [StableWrapperCodeGen, Guid("AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE")]
                public struct TestStruct
                {
                    public int Value;
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_AAAAAAAABBBBCCCCDDDDEEEEEEEEEEEE : UnityStableReference.StableWrapper<TestNamespace.TestStruct> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task GeneratesWrapperForGenericClasses()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            namespace TestNamespace
            {
                [StableWrapperCodeGen, Guid("AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE")]
                public class GenericClass<T>
                {
                    public T Value;
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_AAAAAAAABBBBCCCCDDDDEEEEEEEEEEEE : UnityStableReference.StableWrapper<TestNamespace.GenericClass<T>> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task GeneratesWrapperForClassInGlobalNamespace()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            [StableWrapperCodeGen, Guid("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB")]
            public class GlobalClass
            {
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB : UnityStableReference.StableWrapper<GlobalClass> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task GeneratesWrapperForInternalClass()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            namespace TestNamespace
            {
                [StableWrapperCodeGen, Guid("CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCCCC")]
                internal class InternalClass
                {
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC : UnityStableReference.StableWrapper<TestNamespace.InternalClass> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task GeneratesWrapperWhenAttributesInDifferentOrder()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            namespace TestNamespace
            {
                [Guid("DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD"), StableWrapperCodeGen]
                public class AttributeOrderClass
                {
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD : UnityStableReference.StableWrapper<TestNamespace.AttributeOrderClass> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task GeneratesWrapperForClassImplementingInterface()
    {
        // Arrange
        var source = """
            using System;
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            namespace TestNamespace
            {
                public interface ITestInterface
                {
                    void DoSomething();
                }

                [StableWrapperCodeGen, Guid("EEEEEEEE-EEEE-EEEE-EEEE-EEEEEEEEEEEE")]
                public class InterfaceClass : ITestInterface, IDisposable
                {
                    public void DoSomething() { }
                    public void Dispose() { }
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE : UnityStableReference.StableWrapper<TestNamespace.InterfaceClass> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task HandlesGuidWithoutDashes()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            namespace TestNamespace
            {
                [StableWrapperCodeGen, Guid("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF")]
                public class NoDashesClass
                {
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF : UnityStableReference.StableWrapper<TestNamespace.NoDashesClass> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task HandlesMultipleAssemblyAttributes()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]
            [assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SomeAssembly")]

            namespace TestNamespace
            {
                [StableWrapperCodeGen, Guid("AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA")]
                public class TestClass
                {
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA : UnityStableReference.StableWrapper<TestNamespace.TestClass> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task GeneratesWrapperForPartialClass()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            namespace TestNamespace
            {
                [StableWrapperCodeGen, Guid("11112222-3333-4444-5555-666677778888")]
                public partial class PartialClass
                {
                    public int Property1 { get; set; }
                }

                public partial class PartialClass
                {
                    public string Property2 { get; set; }
                }
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_11112222333344445555666677778888 : UnityStableReference.StableWrapper<TestNamespace.PartialClass> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }

    [TestMethod]
    public async Task GeneratesWrapperForRecord()
    {
        // Arrange
        var source = """
            using System.Runtime.InteropServices;
            using UnityStableReference;

            [assembly: StableWrapperCodeGen]

            namespace TestNamespace
            {
                [StableWrapperCodeGen, Guid("99998888-7777-6666-5555-444433332222")]
                public record TestRecord(string Name, int Age);
            }
            """;

        var expectedOutput = """
            // <auto-generated/>
            namespace __StableWrapper__
            {
            [System.Serializable] public class StableWrapper_99998888777766665555444433332222 : UnityStableReference.StableWrapper<TestNamespace.TestRecord> { }
            }
            """;

        // Act & Assert
        await VerifySourceGen.VerifyGeneratorAsync(source, "StableWrapper.g.cs", expectedOutput);
    }
}

